In [14]:
# SPLIT THE STRING
s = "Hello Myself KmRamya"
s.split(" ")

['Hello', 'Myself', 'KmRamya']

In [15]:
planet = "Earth"
diameter = 12742
print("The diameter of ", planet, " is ", diameter, " kilometers.")

The diameter of  Earth  is  12742  kilometers.


In [16]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]


'hello'

In [17]:
#NUMPY
import numpy as np

In [18]:
# Create an array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
# Create an array of 10 fives
np.arange(20,35,2)

array([20, 22, 24, 26, 28, 30, 32, 34])

In [20]:
# Create 3x3 matrix values ranging from 0-8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
# Concatenate a and b
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [22]:
#PANDAS
import pandas as pd

In [23]:
# Create DataFrame Using 3Rows and 2Columns
data = {'Name':['KmRamya', 'Lucky', 'Nimmy'], 'Occupation': ['Student', 'Lawyer', 'Doctor']}
df = pd.DataFrame(data)
df

Name Occupation
0  KmRamya    Student
1    Lucky     Lawyer
2    Nimmy     Doctor

In [24]:
#Generate Series of dates from Jan1-2023 to 10Feb-2023
ser = pd.date_range('1/1/2023', '2/10/2023')
ser

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')

In [25]:
#Create 2D List to Dataframe
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [26]:
df1 = pd.DataFrame(lists)
df1

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24